### ISSUE TITLE
Form as template: template/element

### ISSUE THREAD

**Issue by dotinspace** [emil0r/ez-wire#4]
Form as template does not seem to behave as `form/as-wire` in terms of `:template/element`, which does not seem to allow fragment, e.g.:

The following works as expected:
```clojure
[form/as-wire
        {:wiring/element [:<>]
         :wiring
         [:<>
          [:td [:div
                [:span.field :$ns/key1.field]
                [:span.error :$ns/key1.errors]]]
          [:td [:div
                [:span.field :$ns/key2.field]
                [:span.error :$ns/key2.errors]]]
          ...
```

This, however, doesn't:
```clojure
[form/as-template
        {:template/element [:<>]
         :template
         [:<>
          [:td [:div
                [:span.field :$field]
                [:span.error :$errors]]]]}
         form]
```

**Comment by emil0r** [comment]
as-wire does not have `:wiring/element`. The reason it works is that `:wiring` is taken as a whole and does everything. In `:wiring` the content is wrapped in a `:<>` element.

`:template/element` looks like it would end up as `[[:<>] [:<> [:td [:div [:span.field :$field]
                [:span.error :$errors]]]]`. Try settings it to `:<>` instead of having it wrapped in brackets.

**Comment by dotinspace** [comment]
Thanks, that did indeed work.
